[build]
  base = "apps/web/"
  command = "npm run build"
  publish = "build/"

[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "17.2.0"

[functions]
  node_bundler = "esbuild"
